# Site settings
title: Yuan Luna
email: yuanfengluna@gmail.com
description: >-
  Agentic AI Solutions & Product Engineering
baseurl: ""
url: "https://yuanluna.com"

# Build settings
theme: minima
plugins:
  - jekyll-feed
